spring.datasource.url=jdbc:postgresql://localhost:5432/attendance_db
spring.datasource.username=abdulsamishaikh
spring.datasource.password=aszxaszx
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=MG8PJbf1g5ajhADd18f8pqDibsXa2B3EeQ3Vc1k18SE=